---
apiVersion: v2
name: grafana
description: A helm chart for an app
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: 10.0.0
    repository: https://grafana.github.io/helm-charts