---
grafana:
  fullnameOverride: grafana
  replicas: 1
  adminUser: admin
  adminPassword: StrongPassword
  priorityClassName: system-cluster-critical
  serviceMonitor:
    enabled: false
    interval: 5m
    scrapeTimeout: 30s
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi