apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 
  description: 
  annotations:
    github.com/project-slug: pcnuness/platform-addons-charts
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "pcnuness"