---
crossplane:
  fullnameOverride: crossplane
  replicas: 3
  priorityClassName: system-cluster-critical
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  # AWS Provider configuration for PROD environment
  args:
    - --enable-composition-revisions
    - --enable-composition-functions
