---
# Default values for grafana
# These are base values that can be overridden per cluster
grafana:
  fullnameOverride: grafana
  replicas: 1
  adminUser: admin
  # adminPassword should be overridden per cluster
  adminPassword: ChangeMe
  priorityClassName: system-cluster-critical
  serviceMonitor:
    enabled: false
    interval: 5m
    scrapeTimeout: 30s
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
