---
apiVersion: v2
name: metrics-server
description: A helm chart for metrics-server
type: application
version: 0.1.0
dependencies:
  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server/