---
metrics-server:
  fullnameOverride: metrics-server-charts-develop
  replicas: 2
  priorityClassName: system-cluster-critical
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  metrics:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: 5m
    scrapeTimeout: 30s
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  args:
    - --kubelet-insecure-tls
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi
